baseurl = "https://guangxuanliu.github.io"
title = "刘光轩的个人博客"
author = "刘光轩"
canonifyurls = true
languagecode = "zh-cn"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "刘光轩的个人博客"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/nanxstats"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/nanxstats"
    weight = 4
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5
